permalink: /:title/
markdown: kramdown
kramdown:
    syntax_highlighter_opts:
        # Disable Rouge syntax highlighter to use a JS-based one
        disable: true

# Jekyll plugins
gems:
    - jekyll-sitemap
    - jekyll-gist
    - jekyll-paginate
    - jekyll-seo-tag

url: http://mnapoli.fr

# Variables used by the SEO plugin
title: Matthieu Napoli
description: Thoughts and experiments about web development and programming
twitter:
    username: matthieunapoli

# Pagination for the article list
paginate: 10          # Posts per page on the blog index
pagination_dir: blog  # Directory base for pagination URLs eg. /blog/page/2/
paginate_path: "/blog/page/:num/"

# Github repositories
github_user: mnapoli
github_repo_count: 10
github_show_profile_link: true
github_skip_forks: true

# Twitter
twitter_user: matthieunapoli
twitter_tweet_button: true

# Disqus Comments
disqus_short_name: mnapoli-blog
disqus_show_comment_count: true

# Top menu bar
navigation:
    - text: Home
      url: /
    - text: Talks
      url: /presentations/
    - text: Projects
      url: /projects/
    - text: Blog archives
      url: /archives/
    - text: About me
      url: /about-me/
    - text: "<i class='icon-rss social-navbar'></i>"
      url: /atom.xml
